### ISSUE TITLE
TypeError: server.connection is not a function

### ISSUE THREAD

**Issue by ypy-pasha** [srinivastamada/NodeRestful#3]
using node v9.5.0

server.connection({
       ^

TypeError: server.connection is not a function
    at Object.<anonymous> (C:\Program Files\nodejs\server.js:21:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

**Comment by reresetyawan** [comment]
using node v10.7.0

I have solved the problem, by changing the code to:

const server = new Hapi.Server({
    host: 'localhost',
    port: 8000
});


/*/ --- before ---
server.connection({
    host: 'localhost',
    port: 8000
});
//*/

i hope this can help you
